### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by fnxpt**

### CODE REVIEW

**Comment by fnxpt** [comment]
@rtfpessoa, thank you for all your support.
I merged the code and created a PR just to fix the remaining issues with the tests.
I fixed all the lines that were wrong, but I saw some issues with files that should have return issues, any idea about this.

**Comment by rtfpessoa** [comment]
After a quick check seems like the parsing of the output is not working. I suggest you use `--reporter json` to avoid spaces problems.

Seems like in `void_return.swift` the patternId returned is )`

**Comment by marlontojal** [comment]
Thanks, I will make the change asap

**Comment by fnxpt** [comment]
@rtfpessoa, it looks good to me, can you have a look

**Comment by rtfpessoa** [comment]
I saw some files that do not have any issues identified. Not sure if you missed them or if it is on purpose:
* trailing_newline.swift
* function_body_length.swift
* trailing_whitespace.swift
* leading_whitespace.swift

The rest looks good.

**Review by rtfpessoa — APPROVED** [review]

**Comment by marlontojal** [comment]
I will remove those files, since they don't generate any issues

**Pull request merged**
