### PR TITLE
[WIP] Circle-CI integration

### PR DESCRIPTION
**Pull request by fnxpt**
- [x] Add Circle-CI 
- [x] Add Tests

### CODE REVIEW

**Comment by fnxpt** [comment]
@rtfpessoa, I made a few tests and I still need to fix a couple of issues, but if you could have a look and tell me if I'm going in the right way

**Comment by rtfpessoa** [comment]
@fnxpt, the tests look great. 
We usually test a couple of patterns to make sure we avoid problems after version updates.

I just noticed we are receiving results for more patterns that the ones being tested. The tool might not be correctly invoked.

**Comment by fnxpt** [comment]
@rtfpessoa I'm not sure if swiftlint supports it, but I will check if we can specify a pattern for each test

**Comment by rtfpessoa** [comment]
@fnxpt I think I might not have explained myself correctly. The idea is for the code to parse the `conf` parameter and invoke the underlying tool with some sort of configuration. In this case I think you will need to generate a `.swiftlint-ci.yml`.

Sorry for the misunderstanding.

**Comment by fnxpt** [comment]
@rtfpessoa, I included a .swiftlint.yml in the tests directories, but in order to disable rules in files I have to specify a comment disabling the rules that I don't want to use for that file.
As far as I know its not possible to set specific rules to specific files.

**Comment by rtfpessoa** [comment]
Maybe you are not getting the big picture here. If you look for example in our ESLint docker https://github.com/codacy/codacy-eslint/blob/master/src/main/scala/codacy/eslint/ESLint.scala#L111 you can see how we do it there. You probably need something similar.

That way you tell the tools what are the patterns and parameters for it to use. Those parameters available in `conf` are then passed by Codacy from the UI.

Also if `conf` is none we should invoke the tool without that config, like you are doing now.

Does this help?

**Comment by fnxpt** [comment]
@rtfpessoa, thank you, I think I understood it. I will make those changes as soon as possible

**Comment by fnxpt** [comment]
@rtfpessoa, can you give me an example of what you use to call the tests. what's the configuration parameter and the files parameter

**Comment by rtfpessoa** [comment]
All the dtos that you receive in the apply method are present in this project https://github.com/codacy/codacy-plugins-api/blob/master/src/main/scala/codacy/docker/api/DockerApi.scala is this what you need?

**Comment by fnxpt** [comment]
@rtfpessoa, when circle-ci runs, internally it calls the docker with the engine in order to perform the tests against it.
When this happens what does the engine receives in the apply function.
I tried to figure out whats being received using a few prints, but I'm unable to see them when it executes.
I think I'm almost there but I just wanted to check if everything is ok, and if its generating a correct yaml file

**Comment by rtfpessoa** [comment]
The Configuration is composed of these objects:

```
case class Configuration(name: Tool.Name, patterns: Option[List[Pattern]])
case class Pattern(patternId: Pattern.Id, parameters: Option[Set[Parameter]])
case class Parameter(name: Parameter.Name, value: JsObject)
```

And the files are just a list of strings.

**Comment by fnxpt** [comment]
Ok but is there any way to replicate what is made by the tests... for instance how can I call this engine with just one pattern and one file

**Comment by fnxpt** [comment]
@rtfpessoa can you check whats wrong in my implementation? It looks like some of files are not returning the expected values and I'm unable to reproduce this

**Comment by rtfpessoa** [comment]
@fnxpt sorry for the delay. I only got time to get to it today.

I did some changes and it seems to be running in #3

**Pull request merged**
